/**
 * AUTOMATION ENGINE FOR GOOGLE FORMS
 * Inspects the linked Google Form and automatically constructs
 * the FIELD_SCHEMA configuration dictionary.
 */

/**
 * Run this function to inspect your form and print the updated JSON schema to the logs.
 */
function generateFormConfigFromForm() {
  // Option A: Pull form ID from fallback settings, or paste your Form ID here
  var fallbackConfig = getFallbackFormConfig();
  var formUrl = fallbackConfig.settings.formBaseUrl;
  
  // Extract Form ID from URL
  var formIdMatch = formUrl.match(/\/d\/([a-zA-Z0-9_-]+)/);
  if (!formIdMatch) {
    throw new Error("Invalid form URL in configuration settings.");
  }
  
  var form = FormApp.openById(formIdMatch[1]);
  var items = form.getItems();
  
  var fieldsSchema = {};

  items.forEach(function(item) {
    var title = item.getTitle();
    var itemId = item.getId();
    var itemType = item.getType();
    
    // Map Google Form Types to schema types
    var schemaType = "text";
    if (itemType === FormApp.ItemType.MULTIPLE_CHOICE || 
        itemType === FormApp.ItemType.LIST || 
        itemType === FormApp.ItemType.CHECKBOX) {
      schemaType = "list";
    } else if (itemType === FormApp.ItemType.PARAGRAPH_TEXT) {
      schemaType = "paragraph";
    }

    // Generate a clean camelCase key for the object
    var keyName = createCamelCaseKey(title);

    // Google Form entry IDs are constructed using the Item ID
    // Note: For standard questions, entry.[itemId] corresponds to the field input name
    fieldsSchema[keyName] = {
      titleMatch: title,
      entryId: "entry." + itemId,
      type: schemaType
    };
  });

  var autoGeneratedConfig = {
    settings: fallbackConfig.settings,
    fields: fieldsSchema
  };

  Logger.log("=== AUTO-GENERATED FORM_CONFIG ===");
  Logger.log(JSON.stringify(autoGeneratedConfig, null, 2));
  
  return autoGeneratedConfig;
}

/**
 * Helper function to convert question titles into clean JavaScript keys.
 * Example: "How would you prefer us to contact you?" -> "howWouldYouPreferUsToContactYou"
 */
function createCamelCaseKey(str) {
  return str
    .replace(/[^a-zA-Z0-9 ]/g, "") // Remove special characters
    .split(" ")
    .map(function(word, index) {
      if (word.length === 0) return "";
      if (index === 0) return word.toLowerCase();
      return word.charAt(0).toUpperCase() + word.slice(1).toLowerCase();
    })
    .join("");
}