/**
 * Main form submission handler.
 * Reads configurations, evaluates submissions, traps bots via Honeypot,
 * and dispatches HTML emails.
 * 
 * @param {Object} e - The Google Form submission event object.
 */
function onFormSubmit(e) {
  const formConfig = getFormConfig();
  const reviewConfig = getReviewConfig();
  const spamConfig = getSpamConfig();

  const adminEmail = (formConfig.settings && formConfig.settings.adminEmail) 
    ? formConfig.settings.adminEmail 
    : 'tom@rd3tech.com';
  
  const formResponse = e.response;
  const itemResponses = formResponse.getItemResponses();
  const submitterEmailFromForm = formResponse.getRespondentEmail();

  let name = '';
  let extractedUserEmail = submitterEmailFromForm || '';
  let userGoal = '';
  let selectedUrgency = '';
  let honeypotValue = '';
  let phone = '';
  let location = '';
  let preferredContact = 'Email';
  let isPreviousCustomer = false;
  let contactingAs = 'Individual';
  let situation = '';
  let timeframe = '';

  const fields = [];

  // Match titles from configuration (lowercased for flexible matching)
  const nameTitle = formConfig.fields.name ? formConfig.fields.name.titleMatch.toLowerCase() : 'name';
  const emailTitle = formConfig.fields.email ? formConfig.fields.email.titleMatch.toLowerCase() : 'email';
  const goalTitle = formConfig.fields.userGoal ? formConfig.fields.userGoal.titleMatch.toLowerCase() : 'goal';
  const urgencyTitle = formConfig.fields.urgency ? formConfig.fields.urgency.titleMatch.toLowerCase() : 'urgency';
  const honeypotTitle = formConfig.fields.honeypot ? formConfig.fields.honeypot.titleMatch.toLowerCase() : 'leave blank';

  itemResponses.forEach(itemResponse => {
    const title = itemResponse.getItem().getTitle();
    const rawResponse = itemResponse.getResponse();
    const lowerTitle = title.toLowerCase();

    // Field mapping
    if (lowerTitle.includes(nameTitle) && !name) name = String(rawResponse);
    if (lowerTitle.includes(emailTitle) && !extractedUserEmail) extractedUserEmail = String(rawResponse);
    if (lowerTitle.includes(goalTitle)) userGoal = String(rawResponse);
    if (lowerTitle.includes(urgencyTitle)) selectedUrgency = String(rawResponse);
    if (lowerTitle.includes(honeypotTitle)) honeypotValue = String(rawResponse);

    if (lowerTitle.includes('phone')) phone = String(rawResponse);
    if (lowerTitle.includes('location') || lowerTitle.includes('address')) location = String(rawResponse);
    if (lowerTitle.includes('preferred contact')) preferredContact = String(rawResponse);
    if (lowerTitle.includes('previous')) isPreviousCustomer = String(rawResponse).toLowerCase().includes('yes');
    if (lowerTitle.includes('as an individual') || lowerTitle.includes('business')) contactingAs = String(rawResponse);
    if (lowerTitle.includes('situation')) situation = String(rawResponse);
    if (lowerTitle.includes('timeframe') || lowerTitle.includes('how soon')) timeframe = String(rawResponse);

    fields.push({
      title: title,
      value: Array.isArray(rawResponse) ? rawResponse : String(rawResponse)
    });
  });

  // =========================================================================
  // HONEYPOT BOT TRAP CHECK
  // =========================================================================
  if (honeypotValue && honeypotValue.trim() !== '') {
    Logger.log('🚫 HONEYPOT TRIPPED: Submission generated by bot. Content: "' + honeypotValue + '"');
    return; // Exit execution early
  }

  // =========================================================================
  // MODERATION & FILTER EVALUATION
  // =========================================================================
  const reviewResult = checkReviewKeywords(userGoal, reviewConfig);
  const spamResult = checkSpamKeywords(userGoal, spamConfig);
  const isUrgent = (selectedUrgency.toLowerCase() === 'high');

  // Format payload objects expected by HTML templates
  const formattedDate = Utilities.formatDate(
    new Date(), 
    Session.getScriptTimeZone(), 
    "dd MMMM yyyy, h:mm a"
  );

  const clientData = {
    name: name || 'Website Visitor',
    firstName: name ? name.split(' ')[0] : 'there',
    email: extractedUserEmail || 'N/A',
    phone: phone || 'N/A',
    location: location || 'N/A',
    preferredContact: preferredContact,
    isPreviousCustomer: isPreviousCustomer,
    contactingAs: contactingAs
  };

  const requestData = {
    situation: situation || userGoal || 'Not specified',
    goal: userGoal || 'Not specified',
    timeframe: timeframe || selectedUrgency || 'Not specified'
  };

  const evalData = {
    isSpam: spamResult.isSpam,
    requiresReview: reviewResult.needsReview,
    isUrgent: isUrgent,
    spamScore: spamResult.isSpam ? 100 : 0,
    statusText: spamResult.isSpam ? 'Flagged Spam' : (reviewResult.needsReview ? 'Requires Review' : 'Passed Security Check'),
    flags: reviewResult.matchedKeywords || [],
    reasons: reviewResult.matchedKeywords || []
  };

  // =========================================================================
  // DYNAMIC SUBJECT LINE PREFIX CONSTRUCTION
  // =========================================================================
  let subjectPrefix = '';
  if (spamResult.isSpam) subjectPrefix += (spamConfig.settings?.flagSubjectPrefix || '[SPAM] ');
  if (isUrgent) subjectPrefix += '[URGENT] ';
  if (reviewResult.needsReview) subjectPrefix += (reviewConfig.settings?.flagSubjectPrefix || '[FLAGGED] ');

  // =========================================================================
  // ADMIN HTML EMAIL DISPATCH
  // =========================================================================
  const adminTemplate = HtmlService.createTemplateFromFile('AdminEmail');
  adminTemplate.submissionDate = formattedDate;
  adminTemplate.client = clientData;
  adminTemplate.request = requestData;
  adminTemplate.eval = evalData;

  const adminHtmlBody = adminTemplate.evaluate().getContent();

  MailApp.sendEmail({
    to: adminEmail,
    subject: `${subjectPrefix}[New Enquiry] ${clientData.name} — RD3 Tech`,
    htmlBody: adminHtmlBody
  });

  // =========================================================================
  // CLIENT CONFIRMATION HTML EMAIL DISPATCH
  // =========================================================================
  if (extractedUserEmail) {
    const clientTemplate = HtmlService.createTemplateFromFile('ClientEmail');
    clientTemplate.submissionDate = formattedDate;
    clientTemplate.client = clientData;
    clientTemplate.request = requestData;

    const clientHtmlBody = clientTemplate.evaluate().getContent();

    MailApp.sendEmail({
      to: extractedUserEmail,
      subject: 'We received your request — RD3 Tech',
      htmlBody: clientHtmlBody
    });
  }
}

/**
 * Loads FORM_CONFIG from Script Properties or falls back to FallbackFormConfig.gs
 */
function getFormConfig() {
  const props = PropertiesService.getScriptProperties();
  const raw = props.getProperty('FORM_CONFIG');
  if (raw) {
    try {
      return JSON.parse(raw);
    } catch (e) {
      Logger.log('Error parsing FORM_CONFIG: ' + e.message);
    }
  }
  return typeof getFallbackFormConfig === 'function' ? getFallbackFormConfig() : { fields: {} };
}

/**
 * Loads URGENCY_CONFIG from Script Properties or falls back to FallbackUrgencyConfig.gs
 */
function getUrgencyConfig() {
  const props = PropertiesService.getScriptProperties();
  const raw = props.getProperty('URGENCY_CONFIG');
  if (raw) {
    try {
      return JSON.parse(raw);
    } catch (e) {
      Logger.log('Error parsing URGENCY_CONFIG: ' + e.message);
    }
  }
  return typeof getFallbackUrgencyConfig === 'function' ? getFallbackUrgencyConfig() : {};
}