/**
 * Main form submission handler.
 * Reads configurations, evaluates submissions, traps bots via Honeypot,
 * and dispatches HTML emails.
 * 
 * @param {Object} e - The Google Form submission event object.
 */
function onFormSubmit(e) {
  const formConfig = getFormConfig();
  const reviewConfig = getReviewConfig();
  const spamConfig = getSpamConfig();

  const adminEmail = (formConfig.settings && formConfig.settings.adminEmail) 
    ? formConfig.settings.adminEmail 
    : 'tom@rd3tech.com';
  
  const formResponse = e.response;
  const itemResponses = formResponse.getItemResponses();
  const submitterEmailFromForm = formResponse.getRespondentEmail();

  let name = '';
  let extractedUserEmail = submitterEmailFromForm || '';
  let userGoal = '';
  let selectedUrgency = '';
  let honeypotValue = '';
  const fields = [];

  // Match titles from configuration (lowercased for flexible matching)
  const nameTitle = formConfig.fields.name.titleMatch.toLowerCase();
  const emailTitle = formConfig.fields.email.titleMatch.toLowerCase();
  const goalTitle = formConfig.fields.userGoal.titleMatch.toLowerCase();
  const urgencyTitle = formConfig.fields.urgency ? formConfig.fields.urgency.titleMatch.toLowerCase() : 'urgency';
  const honeypotTitle = formConfig.fields.honeypot ? formConfig.fields.honeypot.titleMatch.toLowerCase() : 'leave blank';

  itemResponses.forEach(itemResponse => {
    const title = itemResponse.getItem().getTitle();
    const rawResponse = itemResponse.getResponse();
    const lowerTitle = title.toLowerCase();

    // 1. Name Check
    if (lowerTitle.includes(nameTitle) && !name) {
      name = rawResponse;
    }

    // 2. Email Check
    if (lowerTitle.includes(emailTitle) && !extractedUserEmail) {
      extractedUserEmail = rawResponse;
    }

    // 3. User Goal Check
    if (lowerTitle.includes(goalTitle)) {
      userGoal = rawResponse;
    }

    // 4. Urgency Check
    if (lowerTitle.includes(urgencyTitle)) {
      selectedUrgency = String(rawResponse);
    }

    // 5. Honeypot Check
    if (lowerTitle.includes(honeypotTitle)) {
      honeypotValue = String(rawResponse);
    }

    // Store all field responses for HTML table rendering
    fields.push({
      title: title,
      value: Array.isArray(rawResponse) ? rawResponse : String(rawResponse)
    });
  });

  // =========================================================================
  // HONEYPOT BOT TRAP CHECK
  // =========================================================================
  if (honeypotValue && honeypotValue.trim() !== '') {
    Logger.log('🚫 HONEYPOT TRIPPED: Submission generated by bot. Content: "' + honeypotValue + '"');
    Logger.log('--> Execution aborted. Silently dropping email dispatch to save quotas.');
    return; // Exit execution early
  }

  // =========================================================================
  // MODERATION & FILTER EVALUATION
  // =========================================================================
  const reviewResult = checkReviewKeywords(userGoal, reviewConfig);
  const spamResult = checkSpamKeywords(userGoal, spamConfig);
  const isUrgent = (selectedUrgency.toLowerCase() === 'high');

  // =========================================================================
  // DYNAMIC SUBJECT LINE PREFIX CONSTRUCTION
  // =========================================================================
  let subjectPrefix = '';

  if (spamResult.isSpam) {
    const spamPrefix = (spamConfig.settings && spamConfig.settings.flagSubjectPrefix) 
      ? spamConfig.settings.flagSubjectPrefix 
      : '[SPAM] ';
    subjectPrefix += spamPrefix;
  }

  if (isUrgent) {
    subjectPrefix += '[URGENT] ';
  }

  if (reviewResult.needsReview) {
    const reviewPrefix = (reviewConfig.settings && reviewConfig.settings.flagSubjectPrefix) 
      ? reviewConfig.settings.flagSubjectPrefix 
      : '[FLAGGED] ';
    subjectPrefix += reviewPrefix;
  }

  // =========================================================================
  // ADMIN HTML EMAIL DISPATCH
  // =========================================================================
  const adminTemplate = HtmlService.createTemplateFromFile('AdminEmail');
  adminTemplate.name = name;
  adminTemplate.userEmail = extractedUserEmail;
  adminTemplate.fields = fields;

  // Pass evaluation flags to template for banner rendering
  adminTemplate.needsReview = reviewResult.needsReview;
  adminTemplate.matchedKeywords = reviewResult.matchedKeywords;
  adminTemplate.isSpam = spamResult.isSpam;
  adminTemplate.matchedSpamKeywords = spamResult.matchedKeywords;
  adminTemplate.isUrgent = isUrgent;

  const adminHtmlBody = adminTemplate.evaluate().getContent();

  MailApp.sendEmail({
    to: adminEmail,
    subject: `${subjectPrefix}[New Enquiry] ${name ? name : 'Website Visitor'} — RD3 Tech`,
    htmlBody: adminHtmlBody
  });

  // =========================================================================
  // CLIENT CONFIRMATION HTML EMAIL DISPATCH
  // =========================================================================
  if (extractedUserEmail) {
    const clientTemplate = HtmlService.createTemplateFromFile('ClientEmail');
    clientTemplate.name = name;
    clientTemplate.fields = fields;

    const clientHtmlBody = clientTemplate.evaluate().getContent();

    MailApp.sendEmail({
      to: extractedUserEmail,
      subject: 'We received your request — RD3 Tech',
      htmlBody: clientHtmlBody
    });
  }
}

/**
 * Loads FORM_CONFIG from Script Properties or falls back to FallbackFormConfig.gs
 */
function getFormConfig() {
  const props = PropertiesService.getScriptProperties();
  const raw = props.getProperty('FORM_CONFIG');
  if (raw) {
    try {
      return JSON.parse(raw);
    } catch (e) {
      Logger.log('Error parsing FORM_CONFIG: ' + e.message);
    }
  }
  return getFallbackFormConfig();
}

/**
 * Loads URGENCY_CONFIG from Script Properties or falls back to FallbackUrgencyConfig.gs
 */
function getUrgencyConfig() {
  const props = PropertiesService.getScriptProperties();
  const raw = props.getProperty('URGENCY_CONFIG');
  if (raw) {
    try {
      return JSON.parse(raw);
    } catch (e) {
      Logger.log('Error parsing URGENCY_CONFIG: ' + e.message);
    }
  }
  return getFallbackUrgencyConfig();
}